#! /bin/csh -f

if ($#argv > 0) then
  set creab = ($*)
else
  set creab = (creab)
endif

set Codes = (`grep '^\*' strudat | cut -c2-`)

set tA=/tmp/tmp$$A

onintr CLEAN

set delimiter='---------------------------------'

foreach Code ($Codes)
  (echo "$Code"; echo "n") | kriber reacs $creab wriid wrie quit >& $tA
  set nErr =(`grep -i Error   $tA | wc -l`)
  set nWarn=(`grep -i Warning $tA | wc -l`)
  if ($nErr != 0) then
    echo '*** Error(s) while processing *'$Code' ***'
    echo ${delimiter}
  else if ($nWarn != 0) then
    echo '*** Warning(s) while processing *'$Code' ***'
    echo ${delimiter}
  else
    sed 's/^DLS-76  -5    30     0/DLS-76  -5    30     1/' dlsinp > $tA
    mv $tA dlsinp
    dls dlsinp $tA
    set DLSR=(`grep R=SQRT $tA | sed 's/0R=.*=/DLS R =/' | grep -v '\*' | sort +3n | head -1`)
    head -2 strudatn
    set Lit=(`head -3 strudatn | tail -1 | sed 's/ DLS R = .*//'`)
    echo $Lit $DLSR
    head -4 strudatn | tail -1
    set lca=(`grep '^CELL ' nfilea.inp | cut -c21-30`)
    set lcb=(`grep '^CELL ' nfilea.inp | cut -c31-40`)
    set lcc=(`grep '^CELL ' nfilea.inp | cut -c41-50`)
    set lcA=(`grep '^CELL ' nfilea.inp | cut -c51-60`)
    set lcB=(`grep '^CELL ' nfilea.inp | cut -c61-70`)
    set lcG=(`grep '^CELL ' nfilea.inp | cut -c71-80`)
    echo ' '$lca $lcb $lcc $lcA $lcB $lcG
    stripnfilea | tr -c "[0-9][a-z][A-Z] .\012-" "[0*]"
    echo ${delimiter}
  endif
end

CLEAN:

rm -f $tA list strudatn dlsinp nfilea.inp

exit 0
