#! /bin/csh -f

if ($#argv > 0) then
  set iCodes = (`cut -d" " -f1 $1`)
else
  set iCodes = (`grep '^\*' strudat | cut -c2-`)
endif

foreach iC ($iCodes)
  if (`echo $iC | grep '^[0-9]' | wc -l` != 0) then
    set kC = Fw$iC
  else
    set kC =   $iC
  endif

  echo $kC | kriber reacs wrifocus quit
  grep -v '^End$' list > $kC.fis
  rm list
  echo "MinNodeDistance 2.6" >> $kC.fis
  echo "CheckTetrahedralGeometry Off" >> $kC.fis
  if (-f fis_profile_parameters) then
    cat fis_profile_parameters >> $kC.fis
  endif
  echo 'End' >> $kC.fis
end

exit 0
