#! /bin/csh -f

# Convert output of program PEAKFIND to "2Theta Counts"

if      ($#argv == 0) then
  set scl = 1.0
  set pfo = peakfind.out
else if ($#argv == 1) then
  set scl = "$1"
  set pfo = peakfind.out
else
  set scl = "$1"
  set pfo = "$2"
endif

onintr CLEAN


echo '@ s1 linestyle 0'
echo '@ s1 symbol 2'
echo '@ s1 symbol size 0.5'
echo '@ s1 symbol color 2'
echo '@ xaxis  tick out'

grep '  /[ 0-9][ 0-9][ 0-9]$' $pfo | sed 's/\*\*/  /' | sed 's/\// /' > tmp$$
cut -c-8 tmp$$ > tmp$$t
formulc '(c+b)*('"$scl"')' tdricb "%.6g" < tmp$$ > tmp$$c
paste -d" " tmp$$t tmp$$c


CLEAN:

rm -f tmp$$ tmp$$t tmp$$c
exit 0
