#! /bin/csh -f

set progn = $0
set progn = $progn:t

if ($#argv == 0) then
  set inpf = nfilea.inp
else if ($#argv == 1) then
  set inpf = "$1"
else
  echo 'usage: '"$progn"' [nfilea.inp]'
  exit 1
endif

if (! -f "$inpf") then
  echo "$progn"': Cannot open '"$inpf"
  exit 1
endif

set tmpf1=/tmp/${progn}1.$$
set tmpf2=/tmp/${progn}2.$$
set tmpf3=/tmp/${progn}3.$$
set tmpf4=/tmp/${progn}4.$$

onintr CLEAR

grep "NATOM  " "$inpf" | cut -c8-13  > $tmpf1
grep "NATOM  " "$inpf" | cut -c14-21 > $tmpf2
grep "NATOM  " "$inpf" | cut -c22-29 > $tmpf3
grep "NATOM  " "$inpf" | cut -c30-37 > $tmpf4

paste -d' ' $tmpf1 $tmpf2 $tmpf3 $tmpf4

CLEAR:

rm -f $tmpf1 $tmpf2 $tmpf3 $tmpf4

exit 0
