#! /bin/csh -f

set seabcabg = ( \
    1   2    3  5  7    70  80 100 \
    3  15    3  5  7    90 100  90 \
   16  75    3  5  7    90  90  90 \
   76 142    5  5  7    90  90  90 \
  143 194    5  5  7    90  90 120 \
  195 230    7  7  7    90  90  90 )

set tA = /var/tmp/stf$$A

onintr CLEAN

set i = 1

while ($i <= $#seabcabg)
  set s = $seabcabg[$i]
  @ i++
  set e = $seabcabg[$i]
  @ i++
  set a = $seabcabg[$i]
  @ i++
  set b = $seabcabg[$i]
  @ i++
  set c = $seabcabg[$i]
  @ i++
  set A = $seabcabg[$i]
  @ i++
  set B = $seabcabg[$i]
  @ i++
  set G = $seabcabg[$i]
  @ i++

  set j = $s

  while ($j <= $e)
    cat << EOT > $tA
Title SG $j
SpaceGroup  $j
UnitCell  $a $b $c $A $B $G
CatchDistance  1
End
EOT
    focus -TestMoreSpecial=50 $tA
    @ j++
  end
end

CLEAN:

rm -f $tA

exit 0
