dls.x: dls.o clock.o clock_linux.o
	fort77 -static -O -o $@ dls.o clock.o clock_linux.o
#	strip dls.x

.f.o:
	fort77 -O -c $*.f

clock_linux.o: clock_linux.c
	cc -O -ansi -c clock_linux.c

clean:
	rm -f dls.x dls.o clock.o clock_linux.o
