Import("focus_scons_env")

env = focus_scons_env.Clone()
env.StaticLibrary(
  target=["#lib/sginfo"],
  source=[
    "sgvers.c",
    "sgclib.c",
    "sgio.c",
    "sgfind.c",
    "sghkl.c",
    "sgss.c",
    "sgharker.c",
    "sgutil.c",
    "sgcond.c",
    "sgcharmx.c",
    "sggrid.c",
    "sgasym.c"])
